- talent360/evaluaciones/models/pregunta.py
- talent360/evaluaciones/models/respuesta.py
Defectos 3, 4: [Link a defect log](https://docs.google.com/spreadsheets/d/1cnt8TByNr00XKLPOyY5tsA11Mlh9DvySryFniZRtN-8/edit#gid=0&range=B20:M21)
Se agrega relación entre respuesta y evaluación y se corrige relación entre pregunta y respuesta.
- Se agrega relación entre respuesta y evaluación 
- Se corrige relación entre pregunta y respuesta. Estaba invertida (many2one a one2many)
> fix(Modelos): Se arregla defectos con id 3 y 4

- unitTest.ps1
Esta función, simplificara el proceso de correr las pruebas unitarias, al simplemente correr solamente el comando "unitTest.ps1", no hace ningun cambio a la funcionalidad, solo evita el proceso de tener que copiar todo el comando completo de init.ps1.
- Añadir el archivo "unitTest.ps1"
N/A
N/A
N/A
N/A
N/A
N/A
> Comando para unit tests

- talent360/evaluaciones/models/evaluacion.py
- talent360/evaluaciones/models/evaluacion_360.py
- talent360/evaluaciones/views/crear_evaluaciones_360.xml
- talent360/evaluaciones/views/evaluaciones_menus.xml
Se corrige el orden y nombre de los menus, adicionalmente se agrega descirpcion al crear evaluacion 360
- Ids de menus
- Nombres de botones de menus
- Se agrega descripcion en crear evaluacion 360
NA
NA
NA
NA
NA
Marcar pruebas realizadas. No es obligatorio hacer todas.
> Fix de orden en menus

- talent360/evaluaciones/models/usuario_evaluacion_rel.py
Agrega el atributo contestada como Boolean al modelo Usuario_Evaluacion_rel
> fix Usuario_Evaluacion_Rel

- talent360/evaluaciones/__manifest__.py
- talent360/evaluaciones/views/crear_evaluacion_clima.xml
- talent360/evaluaciones/views/evaluaciones_views.xml
Se vincula al id de vista correcto
> fix(Semaforización): Se vincula correctamente la vista

- talent360/evaluaciones/views/evaluaciones_menus.xml
- talent360/evaluaciones/views/evaluaciones_views.xml
> fix(Reportes): Se conecta al menu

- talent360/evaluaciones/views/evaluaciones_responder.xml
Permite dar click en toda la casilla al responder las preguntas
> Fix(responder evaluaciones): Permite dar click a toda la casilla

- talent360/evaluaciones/views/evaluaciones_responder.xml
Aumente el tamaño de la fuente para que sea mas legible
- Cambio en la  <div class="o_survey_question_title mb-3"  style="font-size: 20px;"> añadiendo el "Style"
> Fix defectos mike

- talent360/evaluaciones/views/evaluaciones_menus.xml
Se desconecta boton evaluaciones 360
> Fix(evaluaciones 360: Se desconecta boton evaluaciones 360

- talent360/evaluaciones/models/usuario_evaluacion_rel.py
Se arregla el envio de correos
- No se contaba con el correo de origen para mandarlos
> RF14 & R40

- talent360/evaluaciones/views/evaluaciones_views.xml
fix 159
se cambia el dominio de la vista
> fix: Se muestran todas las evaluaciones contestadas

- talent360/evaluaciones/views/evaluaciones_views.xml
se cambia de nombre a boton de detalle respuestas de asignados
> fix: se cambia de nombre al boton

- talent360/evaluaciones/controllers/evaluaciones.py
- talent360/evaluaciones/models/evaluacion.py
- talent360/evaluaciones/models/opcion.py
- talent360/evaluaciones/models/pregunta.py
- talent360/evaluaciones/models/res_users.py
- talent360/evaluaciones/models/respuesta.py
- talent360/evaluaciones/models/usuario_evaluacion_rel.py
- talent360/evaluaciones/tests/test_reportes.py
> chore: fixes in pylint

- talent360/evaluaciones/models/evaluacion.py
La función checar_fechas valida que el año no sea menor al 2024.
Linea 84 check_fechas
> fix(Evaluacion): Fixed defect No. 208

- talent360/evaluaciones/models/usuario_evaluacion_rel.py
prints en lugar de loggers
Linea 132 & 153.
- "print en lugar de logger
print(""No se encontró un usuario asociado"")"
- "print en lugar de logger
print(f""Nombre:{nombre}\nCorreo:{correo}\nURL: {evaluacion_url}"")"
> fix(Evaluacion): Fix 219 & 220 defects, changing prints for logger

- talent360/evaluaciones/views/evaluaciones_views.xml
> fix: Elipsis en titulo

- talent360/evaluaciones/views/evaluaciones_templates.xml
Cambiar nombre de funcion para que siga estandares
> fix(reportes): change function name

- talent360/evaluaciones/models/evaluacion.py
- talent360/evaluaciones/views/asignar_usuarios_externos_template.xml
> fix: defect 231

- talent360/evaluaciones/models/evaluacion.py
- talent360/evaluaciones/views/crear_evaluacion_clima.xml
- talent360/evaluaciones/views/evaluaciones_views.xml
> fix(evaluacion): Fixed defect 228 & 232

- talent360/evaluaciones/models/evaluacion_clima.py
Se agrega mensaje de error cuando los techos son iguales para mayor entendimiento
> fix: se agrega mensaje de error cuando los techos son iguales

- talent360/evaluaciones/models/usuario_externo.py
- talent360/evaluaciones/static/src/scss/resp_tree.css
- talent360/evaluaciones/views/asignar_usuarios_externos_template.xml
- talent360/evaluaciones/views/crear_evaluacion_clima.xml
- talent360/evaluaciones/views/evaluaciones_views.xml
hotfix de typos en la parte de asignar usuarios externos, y cambio en botones para mejorar UX
> fix(asignrExternos):typos y UX

- talent360/evaluaciones/static/src/js/survey_result.js
> fix: Se arreglan labels en radio

- talent360/evaluaciones/static/src/js/survey_result.js
- talent360/evaluaciones/static/src/scss/survey_templates_results.scss
- talent360/evaluaciones/views/evaluaciones_templates.xml
- talent360/evaluaciones/views/portada_clima.xml
Para la vista del reporte de pdf  se arreglo que las graficas se cortaran por hoja
> Fix uri 10

- talent360/evaluaciones/static/src/js/survey_result.js
- talent360/evaluaciones/views/evaluaciones_templates.xml
> fix:defects

- talent360/evaluaciones/__manifest__.py
> fix: manifest

- talent360/evaluaciones/views/evaluaciones_responder.xml
> Fix responsividad responder evaluaciones

- talent360/evaluaciones/static/src/scss/survey_templates_results.scss
- talent360/evaluaciones/views/reporte_clima_template.xml
- talent360/evaluaciones/views/reporte_generico_template.xml
- talent360/evaluaciones/views/reporte_nom_035_template.xml
> Fix responsividad reportes

- talent360/evaluaciones/models/__init__.py
- talent360/evaluaciones/models/objetivo.py
- talent360/evaluaciones/models/usuario_objetivo_rel.py
- talent360/evaluaciones/security/ir.model.access.csv
- talent360/evaluaciones/views/evaluaciones_menus.xml
- talent360/evaluaciones/views/objetivos_views.xml
Como cliente de CR quiero consultar los colaboradores que tienen objetivos de desempeño para monitorear su avance
- Se agregó una vista donde se puede ver, en forma de kanban, los objetivos de cada colaborador
S - 2
Marcar pruebas realizadas. No es obligatorio hacer todas.
> RF 36 | Consultar colaboradores con objetivos de desempeño

- talent360/evaluaciones/models/evaluacion.py
Se quita html en el campo de contenido de correo y se agrega text
> fix(evaluacion): content for email is now text

- talent360/evaluaciones/views/crear_evaluacion_clima.xml
- talent360/evaluaciones/views/evaluaciones_views.xml
> fix(evaluaciones): Regresar campo formato escalar

- talent360/evaluaciones/views/reporte_clima_template.xml
> fix: borrar letra d de resumen clima

- talent360/evaluaciones/models/objetivo.py
> fix(53): Fix Campos de Objetivos

- talent360/evaluaciones/models/usuario_objetivo_rel.py
- talent360/evaluaciones/views/wizards_views.xml
> fix(MBI1.54): Block create and export from filters

- talent360/evaluaciones/models/respuesta.py
- talent360/evaluaciones/views/evaluaciones_views.xml
Description of the issue/feature this PR addresses:
- Se podían duplicar y eliminar las respuestas de un asignado a una evaluación. 
- No se veían las respuestas a las preguntas de una evaluación.
Current behavior before PR:
- Se duplicaban y eliminaban respuestas. 
- No aparecían las respuestas a las evaluaciones.
Desired behavior after PR is merged:
- Ya no se pueden ni duplicar ni eliminar respuestas de una evaluación.
- Ya aparecen las respuestas de las evaluaciones.
---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
> Defectos 49 y 62

- talent360/evaluaciones/views/evaluaciones_views.xml
> fix: boton reporte personalizado

- talent360/evaluaciones/views/reporte_clima_template.xml
> fix: MBI1.68

- talent360/evaluaciones/views/reporte_generico_template.xml
> fix(generico):Poner al reporte genérico botón de exportar

- talent360/evaluaciones/models/evaluacion.py
- talent360/evaluaciones/models/respuesta.py
> fix: defect 80

- talent360/evaluaciones/models/evaluacion.py
- talent360/evaluaciones/views/crear_evaluacion_clima.xml
> Fix(evaluaciones):nombres default evaluacion

- talent360/evaluaciones/models/objetivo.py
- talent360/evaluaciones/models/usuario_objetivo_rel.py
- talent360/evaluaciones/views/objetivos_views.xml
Se arreglaron los defects 81, 82 y 83
> fix(Defects): Fix defects for objectives

- talent360/evaluaciones/models/objetivo.py
- talent360/evaluaciones/views/objetivos_views.xml
> fix: 86-88

- talent360/evaluaciones/views/crear_evaluacion_clima.xml
- talent360/evaluaciones/views/evaluaciones_views.xml
Added instructions for every page inside every evaluation
> fix(74): added instructions for each page in evaluations

- talent360/evaluaciones/controllers/__init__.py
- talent360/evaluaciones/controllers/plan_accion.py
- talent360/evaluaciones/models/__init__.py
- talent360/evaluaciones/models/plan_accion.py
- talent360/evaluaciones/tests/__init__.py
- talent360/evaluaciones/tests/test_plan_accion.py
Como cliente de CR quiero generar un plan de acción para mejorar mi desempeño.
- Se agrega el controller plan_accion
- Se agrega el modelo plan_accion
- Se agregan las pruebas unitarias en el archivo test_plan_accion.py
M - 3
Marcar pruebas realizadas. No es obligatorio hacer todas.
> RF18 Generar un plan de acción

- talent360/evaluaciones/controllers/evaluaciones.py
- talent360/evaluaciones/models/opcion.py
- talent360/evaluaciones/static/src/js/survey_result.js
> fix: 109, 110

- talent360/evaluaciones/models/evaluacion.py
- talent360/evaluaciones/models/niveles.py
Correcciones de la validación de MBI 1.0
- Nuevas validaciones
- Cambiar la ponderación de integer a float
> Corrección RF51 Semaforización

- talent360/evaluaciones/models/objetivo.py
> fix(MBI1.99): Fix division by zero in objectives

- requirements.txt
- talent360/evaluaciones/__manifest__.py
- talent360/evaluaciones/controllers/evaluaciones.py
- talent360/evaluaciones/data/data.xml
- talent360/evaluaciones/models/__init__.py
- talent360/evaluaciones/models/evaluacion.py
- talent360/evaluaciones/models/pregunta.py
- talent360/evaluaciones/models/res_company.py
- talent360/evaluaciones/models/res_users.py
- talent360/evaluaciones/models/usuario_externo.py
- talent360/evaluaciones/models/usuario_objetivo_rel.py
- talent360/evaluaciones/security/ir.model.access.csv
- talent360/evaluaciones/static/csv/template_usuarios_externos.csv
- talent360/evaluaciones/static/src/js/survey_result.js
- talent360/evaluaciones/views/reporte_generico_template.xml
- talent360/evaluaciones/wizards/asignar_usuarios_exernos_wizard.py
Como cliente de CR quiero agregar datos demográficos a mis empleados y que esto se refleje en los reportes
- Se cargan atributos extra.
- Se crean dinámicamente las columnas para los atributos externos en la plantilla de usuario externo
- Se muestran los atributos extra en los reportes
- Se permite filtrar por los atributos extra
- Los atributos extra se omiten is no tienen datos
- Se agregan los atributos extra al exportar respuestas
XL - 8
Marcar pruebas realizadas. No es obligatorio hacer todas.
> RF 56 | Agregar datos demográficos

- requirements.txt
- talent360/evaluaciones/__manifest__.py
- talent360/evaluaciones/models/__init__.py
- talent360/evaluaciones/models/objetivo.py
- talent360/evaluaciones/models/objetivo_progreso.py
- talent360/evaluaciones/security/ir.model.access.csv
- talent360/evaluaciones/views/mis_objetivos_views.xml
- talent360/evaluaciones/views/modificar_progreso_wizard.xml
- talent360/evaluaciones/views/objetivos_views.xml
- talent360/evaluaciones/wizards/__init__.py
- talent360/evaluaciones/wizards/modificar_progreso.py
Como cliente de CR quiero modificar los resultados de avance de objetivo para tener flexibilidad con respecto a factores externos que pudieran alterar los resultados.
- Se creó el modelo objetivo_progreso
- Se creó el modelo del wizard modificar_progreso
- Se creó la vista del wizard modificar_progreso_wizard
- Se modificó la vista de mis_objetivos_views
- Se modificó la vista de objetivos_views
- Se añadieron los permisos correspondientes para las vistas
L - 5
- [Pagina de historial colaborador](https://github.com/Black-Dot-2024/cr-blackdot/assets/88916058/05ea480a-51e6-4ce3-b927-a31c7d27d851)
- [Modificar progreso](https://github.com/Black-Dot-2024/cr-blackdot/assets/88916058/79b360db-5591-4f0f-ac15-064303ba4bbf)
- [Pagina de historial …
> RF27 Modificación de resultados de evaluación

- talent360/evaluaciones/models/evaluacion.py
- talent360/evaluaciones/views/evaluaciones_views.xml
Fix defects MBI1.120, MBI1.121 y MBI1.122
> fix(MBI.120): Fix defects MBI1.120, MBI1.121 y MBI1.122

- talent360/evaluaciones/views/evaluaciones_views.xml
Fix para que cuando una evaluacion CLIMA este abierta, no se puedan agregar, editar ni eliminar preguntas
> fix(Preguntas): Bloquear preguntas de evaluaciones CLIMA

- talent360/evaluaciones/static/src/scss/survey_templates_results.scss
#fix(reporte):Corregir que exportar corta el título
> fix(reporte):Corregir que exportar corta el título

- talent360/evaluaciones/static/src/js/label_width.js
- talent360/evaluaciones/views/evaluaciones_responder.xml
- talent360/evaluaciones/views/mis_objetivos_views.xml
- talent360/evaluaciones/views/registrar_avance_wizard.xml
> Merge dev mbi2

- talent360/evaluaciones/models/objetivo.py
- talent360/evaluaciones/views/modificar_progreso_wizard.xml
- talent360/evaluaciones/wizards/modificar_progreso.py
Cambios a petición del cliente
> Fix RF27 Cambio de atributo que modifica el progreso
